### ISSUE TITLE
how get Job Copies?

### ISSUE THREAD

**Issue by jonyrh** [RWarnecke/TPrinterInfo#1]
how get Job Copies?

i try insert function , but Job Copies always 1...

TPrinterCustom = class(TComponent)
...
function GetJobCopies: Integer;
...
TPrnJobInfo = class(TPrinterCustom)
  public
...
 property JobCopies     : Integer  read GetJobCopies;
...

function TPrinterCustom.GetJobCopies: Integer;
type
  TJobs  = array [0..1000] of JOB_INFO_2;
  PJobs = ^TJobs;
var
  hPrinter, DevM: THandle;
  bytesNeeded, numJobs: Cardinal;
  pJ: PJobs;
begin
  Result := 0;
  if FAllInfos.Count <> 0 then
  begin
    PPrinter := FAllInfos.Items[FPrinterIndex];
    Printer.GetPrinter(PPrinter^.pPrinterName, PPrinter^.pDriverName, PPrinter^.pPortName, DevM);
{$IFDEF DELPHI10_UP}
    if not OpenPrinter(PPrinter^.pPrinterName, hPrinter, nil) then
      RaiseLastWin32Error;
{$ELSE}
    if OpenPrinter(PPrinter^.pPrinterName, hPrinter, nil) then
{$ENDIF}
    try
      EnumJobs(hPrinter, 0, 1000, 2, nil, 0, bytesNeeded, numJobs);
      pJ := AllocMem(bytesNeeded);
{$IFDEF DELPHI10_UP}
      if not EnumJobs(hPrinter, 0, 1000, 2, pJ, bytesNeeded, bytesNeeded, numJobs) then
        RaiseLastWin32Error;
{$ELSE}
      if EnumJobs(hPrinter, 0, 1000, 2, pJ, bytesNeeded, bytesNeeded, numJobs) then
{$ENDIF}
      Result := pJ^[FJobIndex].pDevMode^.dmCopies; **// RESULT FOR COPIES**
    finally
      ClosePrinter(hPrinter);
    end;
  end;
end;

**Comment by RWarnecke** [comment]
Thank you for this code. Please write these function as a pull request here on github. It is easier to merged it as an issue.

**Comment by jonyrh** [comment]
whis new function **NOT work**, numbers of copies always is 1
